from __future__ import annotations

from typing import Protocol

from sample_agents.domain.models import (
    AgentRun,
    ApprovalRequest,
    ApprovalStatus,
    Attachment,
    Message,
    Thread,
    ToolCall,
)


class ConversationRepository(Protocol):
    def create_thread(self, title: str = "New conversation") -> Thread: ...
    def get_thread(self, thread_id: str) -> Thread | None: ...
    def save_message(self, message: Message) -> None: ...
    def list_messages(self, thread_id: str) -> list[Message]: ...
    def save_attachment(self, attachment: Attachment) -> None: ...
    def list_attachments(self, thread_id: str) -> list[Attachment]: ...
    def save_agent_run(self, run: AgentRun) -> None: ...
    def update_agent_run(self, run: AgentRun) -> None: ...
    def save_tool_call(self, call: ToolCall) -> None: ...
    def save_approval(self, approval: ApprovalRequest) -> None: ...
    def get_approval(self, approval_id: str) -> ApprovalRequest | None: ...
    def get_pending_approval(self, thread_id: str) -> ApprovalRequest | None: ...
    def decide_approval(self, approval_id: str, status: ApprovalStatus) -> ApprovalRequest | None: ...
